### ISSUE TITLE
Callback not always the second argument

### ISSUE THREAD

**Issue by omanizer** [pmarkert/async-regex-replace#3]
Nice library...it has been helpful in what I'm using it for.  Thank you!

Consider the case:

```
arr.replace(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/ig, 'test string with url http://www.google.com', function (match, callback) {
  console.log(match, callback)
})
// logs 'http://www.google.com' and 'www.'
// actual callback function would be the 4th argument of the is function instead of second
```

I can reference the callback method just fine using `arguments[arguments.length - 1]`, so this isn't a huge issue, but being that it functions this way it might be beneficial to have callback be the first argument of the function, especially if multiple different regexes are being used.  Also can't use an arrow function for the callback when referencing `arguments` (this just requires me to reference a variable in the parent scope adding an extra couple lines of code here an there, not a huge deal).

Thanks again!

**Comment by pmarkert** [comment]
Great suggestion. I just merged this in as 3.0.0
