### ISSUE TITLE
TypeError: regex.exec is not a function #2

### ISSUE THREAD

**Issue by Gergo4961** [pmarkert/async-regex-replace#5]
Hey, since I can't re-open the closed issue I'll repost with my reply. Original issue:

Ran into this error while trying to edit something using this library:

```
/var/apps/app/node_modules/async-regex-replace/index.js:22
var match = regex.exec(str);
^

TypeError: regex.exec is not a function
```

Update: 

This is the code I'm using, just for testing purposes:

```
'use strict'

var async_regex_replace = require('async-regex-replace');

var skin='~830 keysUnusual Team Captain Sunbeams';
var regex='(~){1}[0-9.]*( ){1}(keysUnusual ){1}';

async_regex_replace.replace(regex, skin, function(callback, match) {
  setTimeout(function() {
    var replacement_value = match.split('').reverse().join('');
    var err = null;
    callback(err, replacement_value);
  }, 1000);
}, function(err, final_result) {
  if(err) { console.log("Error - " + err); }
  else {
    console.log(final_result);
    //> String with xeger to replace
  }
});
```

I'm not that good with regex so you are right, might be the format of my regex or something, any chance you can help me to fix that? I'm probably missing a few characters to make it properly compatible.

Edit.: When testing the regex on a site like http://regexr.com/ it works.

**Comment by pmarkert** [comment]
Your regex variable is being assigned a string value. Try surrounding it
with "/" characters or using the RegExp constructor.

**Comment by Gergo4961** [comment]
var regex=/(~){1}[0-9.]*( ){1}(keysUnusual ){1}/;

This fixed it thank you very much for your help!
